M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu24.04.1} date 2025-11-16T08:17:45-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-11-16T08:17:45-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
%
G90
G05
T1
X2.6903Y2.1285
X2.7468Y2.185
X2.86Y2.0153
M30
